### ISSUE TITLE
qtbase-5.6.2 requires libxcb

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/superbuild#3]
The configure step of qtbase tests linking against system libxcb. However, libxcb is not included in the superbuild package set. Is that intended or are there parts of superbuild missing in this repo?

**Comment by dg0yt** [comment]
I never needed to build and distribute xcb.  The superbuild helps to build packages where I don't have distributions: Windows, Mac, Android.

**Comment by lpechacek** [comment]
OK, sorry for brevity. "libxcb is not included ..." stands for "libxcb **package file** is not included ...". I'm trying to produce test OOM build for Android and during the process qtbase build fails due to missing libxcb. Now I'm wondering if I should write the package file or whether the file is sitting somewhere in your build system and was just omitted when publishing superbuild repo at GitHub.

**Comment by dg0yt** [comment]
No, you weren't too brief, but maybe I was?
Xcb was not omitted. You are (silently) expected too install all development libraries from your Linux distribution which are needed to build the Qt package. When crossbuilding for Android or Windows, the superbuild also builds Qt for the linux build host, mostly because of lupdate IIRC.

**Comment by lpechacek** [comment]
Got it. I mistakenly assumed that superbuild is self-contained but the build process obviously uses includes from the host system.

Just for the record, removing libcxb-devel from the system and manually tweaking default/qtbase-5.6.2/src/plugins/platforms/eglfs/deviceintegration/eglfs_kms_egldevice/Makefile upon build failure (drm.h not in the include path -> INCPATH += -I/usr/include/libdrm/) made the build pass on openSUSE Tumbleweed 20171003.

Thanks for the hints, Kai!
