### ISSUE TITLE
PROJ 5.0.0 released

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/superbuild#5]
http://lists.maptools.org/pipermail/proj/2018-March/008098.html

**Comment by dg0yt** [comment]
PROJ 5.0.0 is in Debian testing.
https://tracker.debian.org/pkg/proj

@Symbian9 OpenOrienteering Superbuild uses Debian source tarballs. I'm subscribed to Debian package tracker notifications so relevant updates usually don't go unnoticed.

**Comment by dg0yt** [comment]
https://tracker.debian.org/pkg/proj: [2018-09-21] proj 5.2.0-1 MIGRATED to testing

**Comment by dg0yt** [comment]
- [x] PROJ 6.0.0 in CI
- [ ] PROJ 6.0.0 on OBS

**Comment by dg0yt** [comment]
Now using PROJ 6.0.0 on Azure Pipelines, for CI, and for releasing, for macOS, Android, Windows. No need to update OBS.
